[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/OOtxwJ1E2d0QWoHMFl6-2qh-hMjY0CMq"
arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/OOtxwJ1E2d0QWoHMFl6-2qh-hMjY0CMq"
zksync-sepolia = "https://zksync-sepolia.g.alchemy.com/v2/OOtxwJ1E2d0QWoHMFl6-2qh-hMjY0CMq"

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 500
fail_on_revert = true

[fmt]
tab_width = 2
bracket_spacing = true
single_line_statement_blocks = "preserve"
multiline_func_header = "params_first"

remappings = [
  '@forge-std/=lib/forge-std/src/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@chainlink-ccip/=lib/chainlink-ccip/chains/evm/',
  '@chainlink-local/=lib/chainlink-local/',
  '@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/',
  '@chainlink/contracts/=lib/chainlink-ccip/chains/evm/node_modules/@chainlink/contracts/',
  '@openzeppelin/contracts@4.8.3/=lib/chainlink-ccip/chains/evm/node_modules/@openzeppelin/contracts-4.8.3/',
  '@openzeppelin/contracts@5.0.2/=lib/chainlink-ccip/chains/evm/node_modules/@openzeppelin/contracts-5.0.2/',
  '@chainlink/contracts-evm/=lib/chainlink-local/lib/chainlink-evm/contracts/',
  '@chainlink/local/src/=lib/chainlink-local/src/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
