[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/OOtxwJ1E2d0QWoHMFl6-2qh-hMjY0CMq" , arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/OOtxwJ1E2d0QWoHMFl6-2qh-hMjY0CMq" }

remappings = [
    '@forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@chainlink-ccip=lib/chainlink-ccip/',
    '@chainlink-local/=lib/chainlink-local/',
]

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 500
fail_on_revert = true

[fmt]
tab_width = 2
bracket_spacing = true
single_line_statement_blocks = "preserve"
multiline_func_header = "params_first"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
